trigger:
- main

pool:
  name: 'default'      # غيّر اسم الـ pool للي عندك
  demands:
  - Agent.OS -equals Windows_NT
  - dotnet                      # demand على capability اسمها dotnet (تأكد من وجودها عند agent)

variables:
  buildConfiguration: 'Release'
  feed: 'CertTST/ialnagar'  # غيّرها للـ Project/Feed بتاعك

stages:
- stage: Build
  displayName: 'Build & Pack'
  jobs:
  - job: BuildJob
    displayName: 'Build on self-hosted agent'
    steps:

    - powershell: |
        gci env:* | sort-object name | Format-Table -AutoSize | Out-File $env:BUILD_ARTIFACTSTAGINGDIRECTORY\environment-variables.txt
      displayName: 'Dump environment variables to artifact dir'

    - task: NuGetAuthenticate@1
      displayName: 'Authenticate to Azure Artifacts feeds'

    - task: DotNetCoreCLI@2
      displayName: 'Restore packages (from feed)'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
        vstsFeed: '$(feed)'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore'

   
    - task: DotNetCoreCLI@2
      displayName: 'Pack NuGet packages'
      inputs:
        command: 'pack'
        packagesToPack: '**/*.csproj'
        configuration: '$(buildConfiguration)'
        nobuild: true
        includesymbols: true
        outputDir: '$(Build.ArtifactStagingDirectory)'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish pipeline artifact (fast) - drop'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'

    # Push packages to feed ONLY from main branch (safe-guard)
    - task: NuGetCommand@2
      displayName: 'Push packages to Azure Artifacts feed (only on main)'
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
        publishVstsFeed: '$(feed)'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
